export const randomiser = [
  {
    instruction: 'Finish your drink immediately, unaffected by multiplier',
    drinks: 1,
    affects: 'player',
    multipliable: false,
    donatable: false,
  },
  {
    instruction: 'Take 2 drinks',
    drinks: 2,
    affects: 'player',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Donate 3 drinks (You can\'t donate more than 2 drinks to a player!)',
    drinks: 1,
    affects: 'player',
    multipliable: false,
    donatable: true,
  },
  {
    instruction: 'All girls drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'All boys drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Ethnic minorities drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Blondes drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Brunettes drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Redheads drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Blue eyes drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Brown eyes drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Eye colours other than blue or brown drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Left handed players drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Right handed players drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Over 30 year olds drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Under 30 year olds drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Go to the toilet immediately, do not take your drink, try for a tactical',
    drinks: 1,
    affects: 'player',
    multipliable: false,
    donatable: false,
  },
  {
    instruction: 'Everyone takes 1 drink',
    drinks: 1,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
  {
    instruction: 'Everyone but the roller takes 3 drinks',
    drinks: 3,
    affects: 'everyone',
    multipliable: true,
    donatable: false,
  },
];
